name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup JDK 17
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Get local.properties from secret
        run: echo "${{secrets.LOCAL_PROPERTIES }}" > ./local.properties

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.7.0

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run local tests
        run: ./gradlew test

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.2
        with:
          name: app
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload test results
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build-reports
          path: app/build/test-results/test*UnitTest/*.xml

  androidTest:
    needs: build-and-test
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup JDK 17
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.7.0

      - name: Run instrumentation tests
        uses: ReactiveCircus/android-emulator-runner@v2.28.0
        with:
          api-level: 33
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedAndroidTest

      - name: Upload test results
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build-reports
          path: app/build/reports/androidTests/connected
